### ISSUE TITLE
Suggestion: modify craft of spear/warhammer and their stats

### ISSUE THREAD

**Issue by ElMoha943** [TownyAdvanced/TownyCombat#20]
Add option to change the craft recipe of spear/warhammer, also add option to change the % extra damage.

It would be ideal to be able to create multiple types of spears/hammers, different recipes, enchants and damages.

**Comment by Goosius1** [comment]
Hi
- There is a problem with adding configs for the weapon special percentages, because the lore of each previously created item will not change.
- On the general idea of coding a feature to allow server owners to define their own weapons, I'm afraid theres too many things higher up the priority list for that to happen soon, but we can leave the ticket open in cass someone else with coding skills takes an interest in doing that.

**Comment by ElMoha943** [comment]
Hi thanx for answering. Thats a real shame, maybe an alternative could be integration with a third-party item plugin? like ItemsAdder or MMOItems.

**Comment by Goosius1** [comment]
Ah yes, that is an excellent idea which could (potentially) be more feasible.

**Comment by Goosius1** [comment]
Fyi also look at CustomCrafting integration

**Comment by Goosius1** [comment]
This can all be done as follows:

1. On weapon hit, search every line of the weapon lore
2. If it starts with 2 colours, this is a TCM signal e.g "Chatcolor.Brown" + "Chatcolor.brown"
3. Now take the 3rd character (also a colour) and use this to identify the effect(s)

**Comment by ElMoha943** [comment]
> This can all be done as follows:
> 
>     1. On weapon hit, search every line of the weapon lore
> 
>     2. If it starts with 2 colours, this is a TCM signal e.g "Chatcolor.Brown" + "Chatcolor.brown"
> 
>     3. Now take the 3rd character (also a colour) and use this to identify the effect(s)

wouldnt it be easier to add some nbt tag to the item?

**Comment by Goosius1** [comment]
- Well as far as I know, using NBT tags would tie TownyCombat to a particular implementation of the server e.g. minecraft.server.v1_18_R1
- In which case bad things might happen for different server versions.
- Also working with NBT tags code is likely more difficult than working with lore.
- Thus lore is probably easier, and likely more robust
