### ISSUE TITLE
Investigate Possible Horse Lag Issue

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/TownyCombat#25]
- There have been some reports that, generally, horses tend to be hard to use in PVP
- From discord convo with graddod
```
When we were testing horses in PvP, main issue was that enemies saw the horse rider standing in place for some time, even though the horse rider on their side was entirely elsewhere. That always left the horse rider as an easy target who would just get pummeled freely.
Its a bit easier in slower close quarters melee, but the kind of 'hit and run' tactics seemed to fail terribly.

I'm not sure what to make of it, but it always seemed to be a weakness to be on the horse, so maybe damage resistance would give you more capacity for failures.
It can also be hard to hit targets close to you in front of you, as the horse blocks your view and estimating range is harder, this can make timing/aiming your charge correctly harder.
On a side note, we tested some special approaches to mounted combat through using another player as the horse while wearing disguise and riding the player, it actually worked and updated the player's position correctly.
From that I could imagine if someone was able to just make a 'horse appear under you', without actually 'riding the horse', then combat and movement could work normally, even with some speed boost. 
```

**Comment by Goosius1** [comment]
- By giving horses the primary role of long distance shooters, who are immune to bow fire, I may have resolved this issue
- If it turns out there is no lag, no problem, horses can usefully get into melee.
- If it turns out there is a little lag, then also no problem, as they can usefully shoot from distance
- If it turns out there is MAJOR lag, such than neither of these things work,  then this ticket should be revisited.

**Comment by galacticwarrior9** [comment]
FWIW, this problem has never been reported on my server. It's possible a plugin is causing the OP's issue.

**Comment by Goosius1** [comment]
Thank you Zaify. 
- With this new info, I will close this ticket, as lag is not expected in the TCM cavalry role.
- If someone does encounter lag while using cavalry in the TCM tank-like role, we can expect someone to open a ticket, then it can be looked into.
- Note that a lack of lag probably still does not allow us to cast horses in a primarily melee role, due to the visual issue of the horses head getting in the way. But if someone wants this option and has an idea how to do it, they can open a new ticket.
