### ISSUE TITLE
CustomModelData support

### ISSUE THREAD

**Issue by illumeleet** [TownyAdvanced/TownyCombat#52]
Add per-item CustomModelData row in plugin configuration, would allow more customization for resource pack creators

**Comment by Goosius1** [comment]
The two new item effects can already be hooked in to custom items by using a lore line configured in the server config.

Were you unaware of this? (Its ok this is very new)

Or did you know about it and are still requesting a different mechanism for custom items?

**Comment by illumeleet** [comment]
I am aware of that, i prefer using custommodeldata, that's why i'm requesting such feature. Would be great addition.

**Comment by Goosius1** [comment]
Ok cool. Yes I think this can be done for the next pre-release; the code change should be easy enough.
